### ISSUE TITLE
pkgsrc Support

### ISSUE THREAD

**Issue by VehementHam** [stillhq/saDB#1]
In addition to snap support, pkgsrc suport should be added.

**Comment by PizzaLovingNerd** [comment]
this is a system component of stillOS, which does not support pkgsrc.

**Comment by VehementHam** [comment]
That is why I made the issue. It is a feature request. By the way Pkgsrc support would be very easy to add, and I could help add it.

**Comment by PizzaLovingNerd** [comment]
The whole point of saDB is to have a database of curated apps, and I don't want the extra dev maintenance of maintaining another source of apps. stillOS is not even finished and hasn't had a release yet and you are opening feature requests before its even finished.
